apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: holambco-hpa
  namespace: mbco-reto-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: holambco-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50