---
name: Build and Push Image to AZURE ACR

run-name: "Build and Push Image to AZURE ACR SPRINGBOOT"

env:
  AZURE_CONTAINER_REGISTRY: "devopspruebatecylab"
  CONTAINER_NAME: "minimalapi"
  RESOURCE_GROUP: "devops-prueba"
  CLUSTER_NAME: "tecylabtest"
  DEPLOYMENT_MANIFEST_PATH: "your-deployment-manifest-path"

on:
#   push:
#     branches: [ main ]
  workflow_dispatch: {} 
jobs:

  extract-version:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get version from changelog
        id: get_version
        run: |
          VERSION=$(grep -m1 -oP '(?<=## \[)[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md)
          echo "Version found: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    needs: extract-version
    steps:
      - name: Print version from previous job
        run: |
          echo "Version is: ${{ needs.extract-version.outputs.app_version }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push the Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: devopsprueba
          IMAGE_TAG: ${{ needs.extract-version.outputs.app_version }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      # Logs in with your Azure credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_ACCESS_KEY }}
          aws-region: us-east-1     

      # Use kubelogin to configure your kubeconfig for Azure auth
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Update kube config
        run: |
          aws eks update-kubeconfig --region us-east-1 --name eks-cluster-tecylab --region us-east-1

      - name: Create namespace if not exists
        run: |
          kubectl get namespace mbco-reto-ns || kubectl create namespace mbco-reto-ns

      - name: Apply manifest
        run: |
          kubectl apply -n mbco-reto-ns -f ./manifiestos/deployment.yaml
          kubectl apply -n mbco-reto-ns -f ./manifiestos/service.yaml
          kubectl apply -n mbco-reto-ns -f ./manifiestos/ingress.yaml
          kubectl apply -n mbco-reto-ns -f ./manifiestos/hpa.yaml
